services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        ENVIRONMENT: prod
    profiles: ["prod"]
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/staticfiles
      - media_volume:/var/www/media
    depends_on:
      - django
    restart: always
    environment:
      - SERVER_NAME=${SERVER_NAME:-_}  # Default to catch-all if not set

  nginx-dev:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        ENVIRONMENT: dev
    profiles: ["dev"]
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/var/www/html
      - ./media:/var/www/media
    depends_on:
      - django-dev
      - frontend-dev
    networks:
      - app_network

  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
    profiles: ["prod"]
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/var/www/media
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      REDIS_HOST: "redis"
      DEBUG: "False"
      DOMAIN_NAME: boger.dev
      MEDIA_PATH: /var/www/media
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    secrets:
      - django_secret_key
      - recaptcha_secret_key
    depends_on:
      - redis
      - postgres
    restart: always

  django-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    profiles: ["dev"]
    environment:
      DEBUG: "True"
      DOMAIN_NAME: localhost
      MEDIA_PATH: ./media
      DJANGO_SETTINGS_MODULE: "backend.settings"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      REDIS_HOST: "redis"
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - ./backend:/usr/src/app
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
    secrets:
      - django_secret_key
      - recaptcha_secret_key

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
    profiles: ["prod"]
    volumes:
      - media_volume:/var/www/media
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A backend worker -l info --uid=1000 --gid=1000
    secrets:
      - django_secret_key
      - email_host
      - email_port
      - email_host_user
      - email_host_password
    depends_on:
      - redis
      - postgres
      - django
    restart: always

  celery_worker-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    profiles: ["dev"]
    volumes:
      - ./backend:/usr/src/app
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "backend.settings"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A backend worker -l info
    user: celery
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
      - django-dev
    secrets:
      - django_secret_key
      - email_host
      - email_port
      - email_host_user
      - email_host_password

  celery_beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
    profiles: ["prod"]
    volumes:
      - media_volume:/var/www/media
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A backend beat -l info
    secrets:
      - django_secret_key
      - email_host
      - email_port
      - email_host_user
      - email_host_password
    depends_on:
      - redis
      - postgres
      - django
    restart: always

  celery_beat-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    profiles: ["dev"]
    volumes:
      - ./backend:/usr/src/app
    environment:
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "backend.settings"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      POSTGRES_DB: tibiknini
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: celery -A backend beat -l info
    user: celery
    networks:
      - app_network
    depends_on:
      - redis
      - postgres
      - django-dev
    secrets:
      - django_secret_key
      - email_host
      - email_port
      - email_host_user
      - email_host_password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    profiles: ["prod"]
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - DOMAIN_NAME=boger.dev
    networks:
      - app_network

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    profiles: ["dev"]
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - DOMAIN_NAME=nginx-dev
    networks:
      - app_network
    secrets:
      - recaptcha_site_key

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tibiknini
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  static_volume:
  media_volume:
  redis_data:
  postgres_data:

networks:
  app_network:
    driver: bridge

secrets:
  django_secret_key:
    file: ./secrets/django_secret_key.txt
  recaptcha_secret_key:
    file: ./secrets/recaptcha_secret_key.txt
  recaptcha_site_key:
    file: ./frontend/.env
  email_host:
    file: ./secrets/email_host.txt
  email_port:
    file: ./secrets/email_port.txt
  email_host_user:
    file: ./secrets/email_host_user.txt
  email_host_password:
    file: ./secrets/email_host_password.txt
