version: '3.8'

services:
    db:
        image: postgres
        env_file:
            - ./backend/.env
        volumes:
            - dbdata16:/var/lib/postgresql/data # Ensure data persistence across container restarts


    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                ENVIRONMENT: ${ENV:-prod}
        develop:
            watch: # for hot reload during development
                - action: rebuild
                  path: ./frontend
        volumes:
            - ${MEDIA_PATH}:/var/www/media
            - ./backend/staticfiles:/var/www/staticfiles
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - django
        restart: always

    django:
        build: ./backend
        command: gunicorn backend.wsgi:application --workers 3 --bind 0.0.0.0:8000
        depends_on:
            - db
        env_file:
            - ./backend/.env # common settings
            - ./backend/.env.${ENV:-prod} # environment-specific settings
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - ./backend:/usr/src/app
            - dbdata16:/var/lib/postgresql/data
            - ${MEDIA_PATH}:/usr/src/app/media

volumes:
    dbdata16:
        name: tibiknini-dbdata16
