services:
  django:
    image: ghcr.io/${OWNER_LC}/tibiknini:latest
    environment:
      DEBUG: "False"
      DOMAIN_NAME: boger.dev
      MEDIA_PATH: /var/www/media
    restart: always

  nginx:
    image: ghcr.io/${OWNER_LC}/nginx:latest
    volumes:
      - /var/www/media:/var/www/media
    restart: always