services:
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                ENVIRONMENT: ${ENV:-prod}
        develop:
            watch: # for hot reload during development
                - action: rebuild
                  path: ./frontend
        volumes:
            - static_volume:/var/www/staticfiles
            - ./cloudflare:/etc/nginx/ssl
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - django
        restart: always

    django:
        build: ./backend
        command: gunicorn backend.wsgi:application --workers 3 --bind 0.0.0.0:8000
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - ./backend:/usr/src/app
            - static_volume:/usr/src/app/staticfiles
        secrets:
            - django_secret_key
            - recaptcha_secret_key
            - email_host
            - email_port
            - email_host_user
            - email_host_password

secrets:
    django_secret_key:
        file: ./secrets/django_secret_key.txt
    recaptcha_secret_key:
        file: ./secrets/recaptcha_secret_key.txt
    email_host:
        file: ./secrets/email_host.txt
    email_port:
        file: ./secrets/email_port.txt
    email_host_user:
        file: ./secrets/email_host_user.txt
    email_host_password:
        file: ./secrets/email_host_password.txt

volumes:
    static_volume:
        name: tibiknini-static-volume
