version: '3'

services:
    certbot:
        image: certbot/certbot
        volumes:
            - ./tibiknini/etc-letsencrypt:/etc/letsencrypt
            - ./tibiknini/var-lib-letsencrypt:/var/lib/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        restart: always

    db:
        image: postgres
        env_file:
            - ./tibiknini/.env
        volumes:
            - dbdata:/var/lib/postgresql/data # Ensure data persistence across container restarts

    nginx:
        build:
            context: ./tibiknini
            dockerfile: ./nginx/Dockerfile
            args:
                ENVIRONMENT: ${ENV}
        volumes:
            - ./tibiknini/etc-letsencrypt:/etc/letsencrypt:ro
            - ./tibiknini/media:/var/www/media
            - ./tibiknini/staticfiles:/var/www/staticfiles
            - ./frontend/build:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        restart: always

    django:
        build: ./tibiknini
        command: gunicorn tibiknini.wsgi:application --workers 3 --bind 0.0.0.0:8000
        depends_on:
            - db
        env_file:
            - ./tibiknini/.env # common settings
            - ./tibiknini/.env.prod # production-specific settings
            - ./tibiknini/.env.dev # development-specific settings
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - ./tibiknini:/usr/src/app
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
        name: tibiknini_dbdata
        external: true