version: '3.8'

services:
  django:
    image: ghcr.io/${OWNER_LC}/tibiknini:latest
    environment:
      DEBUG: "False"
      DOMAIN_NAME: boger.dev
      MEDIA_PATH: /var/www/media
    restart: always

  celery_worker:
    image: ghcr.io/${OWNER_LC}/tibiknini:latest
    command: celery -A backend worker -l info
    restart: always

  celery_beat:
    image: ghcr.io/${OWNER_LC}/tibiknini:latest
    command: celery -A backend beat -l info
    restart: always

  nginx:
    image: ghcr.io/${OWNER_LC}/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/media:/var/www/media
    restart: always