services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    environment:
      DEBUG: "True"
      DOMAIN_NAME: localhost
      MEDIA_PATH: ./media
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        ENVIRONMENT: dev
    volumes:
      - ./media:/var/www/media
      - ./frontend/dist:/var/www/html