# Generated by Django 5.1.3 on 2024-11-25 00:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("upheld_hidden", "Upheld - Content Hidden"),
                            ("upheld_warning", "Upheld - Warning Issued"),
                            ("upheld_banned", "Upheld - User Banned"),
                            ("rejected", "Rejected - Content Follows Rules"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verdict_note", models.TextField(blank=True)),
                ("action_taken", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Report",
                "verbose_name_plural": "Content Reports",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_reasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_report_reasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Reason",
                "verbose_name_plural": "Report Reasons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("report_created", "Report Created"),
                            ("report_reviewed", "Report Reviewed"),
                            ("content_hidden", "Content Hidden"),
                            ("content_warned", "Warning Issued"),
                            ("content_banned", "User Banned"),
                            ("reason_created", "Report Reason Created"),
                            ("reason_modified", "Report Reason Modified"),
                            ("reason_deactivated", "Report Reason Deactivated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("previous_state", models.JSONField(blank=True, null=True)),
                ("new_state", models.JSONField()),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="moderation.contentreport",
                    ),
                ),
                (
                    "report_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="moderation.reportreason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Action",
                "verbose_name_plural": "Moderation Actions",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reason",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="moderation.reportreason",
            ),
        ),
        migrations.CreateModel(
            name="UserWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged", models.BooleanField(default=False)),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_warnings",
                        to="moderation.contentreport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentreport",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="moderation__content_a4d034_idx",
            ),
        ),
    ]
