# Generated by Django 5.2.5 on 2025-08-23 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('severity', models.CharField(choices=[('low', 'Low - Warning'), ('medium', 'Medium - Content Hidden'), ('high', 'High - User Warning'), ('critical', 'Critical - User Ban')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_regex', models.BooleanField(default=False, help_text='Whether this word should be treated as a regex pattern')),
                ('description', models.TextField(blank=True, help_text='Optional description of why this word is flagged')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bad_words', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_bad_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bad Word',
                'verbose_name_plural': 'Bad Words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ContentAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('flagged_words', models.JSONField(default=list, help_text='List of flagged words found in content')),
                ('severity_score', models.IntegerField(default=0, help_text='Overall severity score (0-100)')),
                ('max_severity', models.CharField(blank=True, choices=[('low', 'Low - Warning'), ('medium', 'Medium - Content Hidden'), ('high', 'High - User Warning'), ('critical', 'Critical - User Ban')], max_length=10, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('content_length', models.IntegerField(default=0)),
                ('language_detected', models.CharField(blank=True, max_length=10)),
                ('action_required', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('auto_hidden', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Analysis Result',
                'verbose_name_plural': 'Content Analysis Results',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderation__content_3d6afc_idx'), models.Index(fields=['severity_score'], name='moderation__severit_78de3a_idx'), models.Index(fields=['action_required'], name='moderation__action__1e923d_idx')],
            },
        ),
    ]
