export const REDIRECT_REASONS = {
    AUTHENTICATED_ONLY: 'AUTHENTICATED_ONLY',
    LIKE_POST: 'LIKE_POST',
    CREATE_POST: 'CREATE_POST',
    EDIT_POST: 'EDIT_POST',
    VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
    FOLLOW_USER: 'FOLLOW_USER',
    REGISTRATION_SUCCESSFUL: 'REGISTRATION_SUCCESSFUL',
    // Add more standardized reasons as needed
};