# Generated by Django 5.1.3 on 2024-11-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment_pinned_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
