# Generated by Django 4.2 on 2023-05-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed_0008_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
