# Generated by Django 5.1.1 on 2024-09-11 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_customuser_profile_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile",
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
