# Generated by Django 4.2 on 2023-05-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=255)),
                ('site_description', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('terms_of_service', models.TextField()),
            ],
        ),
    ]
