# Generated by Django 4.2 on 2023-05-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='tos_version',
            field=models.IntegerField(default=1),
        ),
    ]
