# Generated by Django 4.2 on 2023-05-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_siteinfo_tos_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='type',
            field=models.CharField(choices=[('PRIVACY_POLICY', 'Privacy Policy'), ('TERMS_OF_SERVICE', 'Terms of Service')], default='PRIVACY_POLICY', max_length=20, unique=True),
        ),
    ]
