# Generated by Django 4.2 on 2023-05-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteinfo_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='privacy_policy',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='terms_of_service',
        ),
    ]
