# Generated by Django 4.2 on 2023-05-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_privacy_policy_siteinfo_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
