# Generated by Django 5.1.1 on 2024-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_privacypolicy_document_type_termsofservice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privacypolicy',
            old_name='document_type',
            new_name='title',
        ),
    ]
