# Generated by Django 5.1.3 on 2024-11-25 15:43

import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_privacypolicy_title_alter_termsofservice_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypolicy",
            options={"verbose_name_plural": "Privacy Policies"},
        ),
        migrations.AlterModelOptions(
            name="termsofservice",
            options={"verbose_name_plural": "Terms of Service"},
        ),
        migrations.RenameField(
            model_name="termsofservice",
            old_name="last_updated",
            new_name="last_modified_at",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created this version",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="effective_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 11, 25, 15, 42, 15, 390593, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="last_modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="privacypolicy",
            name="last_modified_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who last modified this version",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who created this version",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="effective_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="last_modified_by",
            field=models.ForeignKey(
                default=1,
                help_text="User who last modified this version",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
