# Generated by Django 5.1.3 on 2024-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_privacypolicy_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privacypolicy",
            options={},
        ),
        migrations.AlterModelOptions(
            name="termsofservice",
            options={},
        ),
        migrations.RenameField(
            model_name="privacypolicy",
            old_name="last_modified_at",
            new_name="last_updated",
        ),
        migrations.RenameField(
            model_name="termsofservice",
            old_name="last_modified_at",
            new_name="last_updated",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="privacypolicy",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="termsofservice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="termsofservice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="termsofservice",
            name="effective_date",
        ),
        migrations.RemoveField(
            model_name="termsofservice",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="termsofservice",
            name="last_modified_by",
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="title",
            field=models.CharField(default="Privacy Policy", max_length=50),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="title",
            field=models.CharField(default="Terms of Service", max_length=50),
        ),
    ]
