# Generated by Django 5.1.3 on 2024-11-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_privacypolicy_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("use_tls", models.BooleanField(default=True)),
                ("from_email", models.EmailField(max_length=254)),
                ("is_configured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "SMTP Settings",
                "verbose_name_plural": "SMTP Settings",
            },
        ),
    ]
