# Generated by Django 5.1.8 on 2025-04-06 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_smtpsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpsettings',
            name='is_configured',
        ),
    ]
