name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set lowercase owner name
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Django image
      uses: docker/build-push-action@v4
      with:
        context: ./tibiknini
        file: ./tibiknini/Dockerfile
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/tibiknini:latest

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build -- --prod

    - name: Build and push NGINX image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./nginx/Dockerfile
        push: true
        tags: ghcr.io/${{ env.OWNER_LC }}/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: SSH and deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          export ENV=prod
          docker-compose -f ~/tibiknini/docker-compose.yml pull
          docker-compose -f ~/tibiknini/docker-compose.yml up -d
